# Generated by Django 3.1.5 on 2021-01-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='click_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
